// Auto-generated by scripts/update-gh-fields.ts
// DO NOT EDIT MANUALLY - Run: bun run update-fields
//
// Last updated: 2025-11-02
// gh CLI version: 2.82.0

/**
 * GitHub CLI JSON field mappings for view and list commands.
 *
 * These field definitions are used to inject --json <fields> when users
 * request TOON or JSON format conversion.
 *
 * Both view commands (issue view, pr view) and list commands (issue list, pr list)
 * require explicit field specification when using --json flag.
 * Deprecated/invalid fields filtered during generation:
 *   issue view:
 *     - projectCards: GraphQL: Projects (classic) is being deprecated in favor of the new Projects experience, see: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/. (repository.issue.projectCards)
 *     - projectItems: GraphQL: Could not resolve to an Issue with the number of 1. (repository.issue)
 *   issue list:
 *     - projectCards: GraphQL: Projects (classic) is being deprecated in favor of the new Projects experience, see: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/. (repository.issues.nodes.0.projectCards)
 *   pr list:
 *     - projectCards: GraphQL: Projects (classic) is being deprecated in favor of the new Projects experience, see: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/. (repository.pullRequests.nodes.0.projectCards)
 *   repo view:
 *     - projects: GraphQL: Projects (classic) is being deprecated in favor of the new Projects experience, see: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/. (repository.projects)
 *   repo list:
 *     - projects: GraphQL: Projects (classic) is being deprecated in favor of the new Projects experience, see: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/. (repositoryOwner.repositories.nodes.0.projects)
 *   release view:
 *     - apiUrl: release not found
 *     - assets: release not found
 *     - author: release not found
 *     - body: release not found
 *     - createdAt: release not found
 *     - databaseId: release not found
 *     - id: release not found
 *     - isDraft: release not found
 *     - isImmutable: release not found
 *     - isPrerelease: release not found
 *     - name: release not found
 *     - publishedAt: release not found
 *     - tagName: release not found
 *     - tarballUrl: release not found
 *     - targetCommitish: release not found
 *     - uploadUrl: release not found
 *     - url: release not found
 *     - zipballUrl: release not found
 *   codespace list:
 *     Note: Fields could not be validated (requires Codespaces access). Manually added from gh CLI available fields.
 *   codespace view:
 *     Note: Fields could not be validated (requires Codespaces access). Manually added from gh CLI available fields.
 */
export const GH_JSON_FIELDS: Record<string, string> = {
  'issue view': 'assignees,author,body,closed,closedAt,closedByPullRequestsReferences,comments,createdAt,id,isPinned,labels,milestone,number,reactionGroups,state,stateReason,title,updatedAt,url',
  'issue list': 'assignees,author,body,closed,closedAt,closedByPullRequestsReferences,comments,createdAt,id,isPinned,labels,milestone,number,projectItems,reactionGroups,state,stateReason,title,updatedAt,url',
  'pr view': 'additions,assignees,author,autoMergeRequest,baseRefName,baseRefOid,body,changedFiles,closed,closedAt,closingIssuesReferences,comments,commits,createdAt,deletions,files,fullDatabaseId,headRefName,headRefOid,headRepository,headRepositoryOwner,id,isCrossRepository,isDraft,labels,latestReviews,maintainerCanModify,mergeCommit,mergeStateStatus,mergeable,mergedAt,mergedBy,milestone,number,potentialMergeCommit,projectCards,projectItems,reactionGroups,reviewDecision,reviewRequests,reviews,state,statusCheckRollup,title,updatedAt,url',
  'pr list': 'additions,assignees,author,autoMergeRequest,baseRefName,baseRefOid,body,changedFiles,closed,closedAt,closingIssuesReferences,comments,commits,createdAt,deletions,files,fullDatabaseId,headRefName,headRefOid,headRepository,headRepositoryOwner,id,isCrossRepository,isDraft,labels,latestReviews,maintainerCanModify,mergeCommit,mergeStateStatus,mergeable,mergedAt,mergedBy,milestone,number,potentialMergeCommit,projectItems,reactionGroups,reviewDecision,reviewRequests,reviews,state,statusCheckRollup,title,updatedAt,url',
  'repo view': 'archivedAt,assignableUsers,codeOfConduct,contactLinks,createdAt,defaultBranchRef,deleteBranchOnMerge,description,diskUsage,forkCount,fundingLinks,hasDiscussionsEnabled,hasIssuesEnabled,hasProjectsEnabled,hasWikiEnabled,homepageUrl,id,isArchived,isBlankIssuesEnabled,isEmpty,isFork,isInOrganization,isMirror,isPrivate,isSecurityPolicyEnabled,isTemplate,isUserConfigurationRepository,issueTemplates,issues,labels,languages,latestRelease,licenseInfo,mentionableUsers,mergeCommitAllowed,milestones,mirrorUrl,name,nameWithOwner,openGraphImageUrl,owner,parent,primaryLanguage,projectsV2,pullRequestTemplates,pullRequests,pushedAt,rebaseMergeAllowed,repositoryTopics,securityPolicyUrl,squashMergeAllowed,sshUrl,stargazerCount,templateRepository,updatedAt,url,usesCustomOpenGraphImage,viewerCanAdminister,viewerDefaultCommitEmail,viewerDefaultMergeMethod,viewerHasStarred,viewerPermission,viewerPossibleCommitEmails,viewerSubscription,visibility,watchers',
  'repo list': 'archivedAt,assignableUsers,codeOfConduct,contactLinks,createdAt,defaultBranchRef,deleteBranchOnMerge,description,diskUsage,forkCount,fundingLinks,hasDiscussionsEnabled,hasIssuesEnabled,hasProjectsEnabled,hasWikiEnabled,homepageUrl,id,isArchived,isBlankIssuesEnabled,isEmpty,isFork,isInOrganization,isMirror,isPrivate,isSecurityPolicyEnabled,isTemplate,isUserConfigurationRepository,issueTemplates,issues,labels,languages,latestRelease,licenseInfo,mentionableUsers,mergeCommitAllowed,milestones,mirrorUrl,name,nameWithOwner,openGraphImageUrl,owner,parent,primaryLanguage,projectsV2,pullRequestTemplates,pullRequests,pushedAt,rebaseMergeAllowed,repositoryTopics,securityPolicyUrl,squashMergeAllowed,sshUrl,stargazerCount,templateRepository,updatedAt,url,usesCustomOpenGraphImage,viewerCanAdminister,viewerDefaultCommitEmail,viewerDefaultMergeMethod,viewerHasStarred,viewerPermission,viewerPossibleCommitEmails,viewerSubscription,visibility,watchers',
  'release view': '',
  'label list': 'color,createdAt,description,id,isDefault,name,updatedAt,url',
  'secret list': 'name,numSelectedRepos,selectedReposURL,updatedAt,visibility',
  'variable list': 'createdAt,name,numSelectedRepos,selectedReposURL,updatedAt,value,visibility',
  'search repos': 'createdAt,defaultBranch,description,forksCount,fullName,hasDownloads,hasIssues,hasPages,hasProjects,hasWiki,homepage,id,isArchived,isDisabled,isFork,isPrivate,language,license,name,openIssuesCount,owner,pushedAt,size,stargazersCount,updatedAt,url,visibility,watchersCount',
  'search issues': 'assignees,author,authorAssociation,body,closedAt,commentsCount,createdAt,id,isLocked,isPullRequest,labels,number,repository,state,title,updatedAt,url',
  'search prs': 'assignees,author,authorAssociation,body,closedAt,commentsCount,createdAt,id,isDraft,isLocked,isPullRequest,labels,number,repository,state,title,updatedAt,url',
  // Codespace fields - manually added due to 403 permissions (requires Codespaces access)
  // Fields extracted from gh CLI error messages, will work when user has proper access
  'codespace list': 'createdAt,displayName,gitStatus,lastUsedAt,machineName,name,owner,repository,state,vscsTarget',
  'codespace view': 'billableOwner,createdAt,devcontainerPath,displayName,environmentId,gitStatus,idleTimeoutMinutes,lastUsedAt,location,machineDisplayName,machineName,name,owner,prebuild,recentFolders,repository,retentionExpiresAt,retentionPeriodDays,state,vscsTarget',
}
